server:
  port: 9998

#mysql配置

spring:
  profiles:
    active: prod
  datasource:
    # url: jdbc:mysql://192.168.1.203:3306/spsv2_formal_09_20?characterEncoding=utf8&useSSL=true&allowMultiQueries=true
    url: jdbc:mysql://192.168.1.62:3306/spsv2_migration_2017092701?characterEncoding=utf8&useSSL=true&allowMultiQueries=true
    username: root
    password: 123456
#    password: admin
    driver-class-name: com.mysql.jdbc.Driver
#    password: iaQEo40CgpXhxYCU33Y9
#日期格式：标准格式
  jackson:
    serialization:
      write-dates-as-timestamps : false
    time-zone: Asia/Shanghai
    property-naming-strategy: SNAKE_CASE
#rabbitmqp配置
  rabbitmq:
    port: 5672
    host: 192.168.1.203
#    host: localhost
    username: admin
    password: admin64661899

#freemaker
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    template-loader-path: classpath:/templates/

#热部署生效
  devtools:
    restart:
      enabled: true
    #设置重启的目录
      additional-paths: src/main/java
    #classpath目录下的WEB-INF文件夹内容修改不重启
      exclude: templates

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.shipparts.uaa.entity


shipparts:
#系统管理员
 administrator:
  username: admin
  password: 123456
#认证服务器做登录认证的参数
 globalSecurity:
  signingKey: shipparts-it-department

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG


#日志配置
logback:
  appname: support-uaa
  logdir: ../../logs/${logback.appname}/

##很重要
#security:
#  oauth2:
#    resource:
#      filter-order: 3