server:
  port: 9999

#mysql配置

spring:
  application:
    name: support-uaa
  profiles:
    active: local

#日期格式：标准格式
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Shanghai
    property-naming-strategy: SNAKE_CASE
#rabbitmqp配置
  rabbitmq:
    port: 5672
    host: 47.104.166.37
    # host: localhost
    username: admin
    password: admin64661899


management:
  security:
    enabled: false




#注册服务
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:8000/eureka/
#  instance:
#    #地址配置
#    hostname: localhost
#    prefer-ip-address: true
#    instance-id: ${eureka.instance.hostname}:${server.port}

shipparts:
#系统管理员
 administrator:
  username: admin
  password: 123456


